# Generated by Django 3.1.2 on 2021-01-16 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0002_auto_20210116_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('job', models.CharField(choices=[('1', 'CONTADOR'), ('2', 'ADMINISTRADOR'), ('3', 'ECONOMISTA'), ('4', 'OTRO')], max_length=1, verbose_name='Trabajos')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
        ),
    ]
