# Generated by Django 3.1.2 on 2021-01-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employed', '0002_auto_20210123_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='employed',
            name='skill',
            field=models.ManyToManyField(to='employed.Skill'),
        ),
    ]
