# Generated by Django 3.1.2 on 2021-01-23 23:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employed', '0003_employed_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='employed',
            name='curriculum',
            field=ckeditor.fields.RichTextField(default='text'),
            preserve_default=False,
        ),
    ]
