# Generated by Django 3.1.2 on 2021-01-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='active',
            field=models.BooleanField(default=False, unique=True, verbose_name='Activo'),
        ),
    ]
